# Specify path to input pdbs
#PDBs: "/home/administrator/phd/crAss_DB/folds"
#PDBs: "/home/administrator/phd/77_test_phages/test_phages_791_pdbs"
PDBs: "/home/administrator/phd/77_test_phages/fabian_phages/pdbs"

#PDBs: "/home/administrator/phd/PhagePleats/test_data"
# genome-protein mapping metadata file
metadata: "/home/administrator/phd/77_test_phages/fabian_phages/new_zip/metadata_proteins.csv"
outdir: "/home/administrator/phd/"

