# Specify path to input pdbs
#PDBs: "test_data/pdbs"
PDBs: "/home/administrator/phd/77_test_phages/fabian_phages/pdbs"

# genome-protein mapping metadata file
#metadata: "test_data/metadata/genome_protein_mapping.csv"
metadata: "/home/administrator/phd/77_test_phages/fabian_phages/new_zip/metadata_proteins.csv"

# Output directory
outdir: "/home/administrator/phd/"

