# Specify path to input pdbs
PDBs: "test_data/pdbs"

# genome-protein mapping metadata file
metadata: "test_data/metadata/genome_protein_mapping.csv"

# Output directory
outdir: "/home/administrator/phd/"

